# vim: set ft=yaml fenc=utf-8 ff=unix sw=2 ts=2 et :
$schema: https://taskfile.dev/schema.json
version: '3'

vars:
  APP_NAME: gcalntfy
  VERSION:
    sh: git describe --tags --always --dirty | sed 's/^v//'
  ARCH: x64

tasks:
  default:
    desc: クリーンビルドを実行
    cmds:
      - task clean
      - task build

  kill:
    desc: 実行中のアプリケーションを強制終了（起動していない場合は無視）
    cmds:
      - cmd: taskkill /IM {{.APP_NAME}}.exe /F
        ignore_error: true

  clean:
    desc: out/ 以下のファイルを削除
    deps: [kill]
    cmds:
      - rm -rf out

  copy-assets:
    desc: ビルド成果物ディレクトリへのアセットコピー
    internal: true
    cmds:
      - cp {{.APP_NAME}}.toml out/
      - cp src/sound.wav out/
      - cp src/app.ico out/
      - cmd: cp -f *.local.* out/
        ignore_error: true

  build:
    desc: 通常ビルド（out/gcalntfy.exe）
    deps: [kill]
    cmds:
      - mkdir -p out
      - pwsh -NonInteractive -File build.ps1 -Version {{.VERSION}}
      - task: copy-assets

  rebuild:
    desc: 実行中のバイナリの停止・クリーンビルド・再起動
    cmds:
      - task: clean
      - task: build
      - pwsh.exe -NoProfile -Command "Start-Process 'out/{{.APP_NAME}}.exe'"

  release:
    desc: リリースビルド（デバッグ情報なし＋最適化）と zip 作成
    deps: [clean]
    cmds:
      - mkdir -p out
      - pwsh -NonInteractive -File build.ps1 -Version {{.VERSION}} -Release
      - task: copy-assets
      - >-
        pwsh -NonInteractive -Command '
        Compress-Archive
        -Path out\{{.APP_NAME}}.exe, {{.APP_NAME}}.toml, out\sound.wav, out\app.ico
        -DestinationPath "out\{{.APP_NAME}}-{{.VERSION}}-{{.ARCH}}.zip"
        -Force'
