# vi: ts=2 sw=2 ff=unix fenc=utf-8
version: '3'

vars:
  VERSION: '1.5.1'

tasks:
  clean:
    desc: ビルド成果物を削除
    dir: gcalntfy
    cmds:
      - rm -rf out

  build:
    desc: gcalntfy をビルド
    dir: gcalntfy
    cmds:
      - taskkill //F //IM gcalntfy.exe 2>/dev/null || true
      - mkdir -p out
      - pwsh -NonInteractive -File build.ps1 -Version {{.VERSION}}
      - cp gcalntfy.toml out/
      - cp src/audio1.opus out/
      - cp src/audio2.opus out/
      - cp src/app.ico out/
      - cp -f *.local.* out/ 2>/dev/null || true

  release:
    desc: リリースビルドと zip 作成
    dir: gcalntfy
    deps: [build]
    cmds:
      - >-
        pwsh -NonInteractive -Command '
        Compress-Archive
        -Path out\gcalntfy.exe, gcalntfy.toml, out\audio1.opus, out\audio2.opus, out\app.ico
        -DestinationPath "out\gcalntfy-{{.VERSION}}-x64.zip"
        -Force'
